@php($creditVariant = $variant ?? 'print')
@php($developerName = trim((string) config('business.developer_name', 'Kisakye Allan')))
@php($developerCompany = trim((string) config('business.developer_company', 'Rolans Software Solutions')))
@php($developerPhone = trim((string) config('business.developer_phone', '')))
@php($developerLine = trim($developerName.($developerCompany !== '' ? ' | '.$developerCompany : '')))

@if ($creditVariant === 'sidebar')
    <div class="sidebar-credit">
        <strong>&copy; 2026 Apples Of Gold System</strong>
        <span>Designed &amp; Developed by {{ $developerLine }}</span>
        @if ($developerPhone !== '')
            <span>Tel: {{ $developerPhone }}</span>
        @endif
    </div>
@else
    <div class="print-credit">
        <div>Generated by Apples Of Gold System</div>
        <div>Designed &amp; Developed by {{ $developerLine }}</div>
        @if ($developerPhone !== '')
            <div>Tel: {{ $developerPhone }}</div>
        @endif
    </div>
@endif
