<?php

use App\Http\Controllers\AccessPreviewController;
use App\Http\Controllers\AdminToolkitController;
use App\Http\Controllers\ActivityLogController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\BusinessSettingsController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\CustomerPaymentController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\CapitalEntryController;
use App\Http\Controllers\CashShiftController;
use App\Http\Controllers\ExpenseController;
use App\Http\Controllers\FollowUpController;
use App\Http\Controllers\ManagementCentreController;
use App\Http\Controllers\MasterDataController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\PurchaseController;
use App\Http\Controllers\PasswordManagementController;
use App\Http\Controllers\QuickCategoryController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\RoleManagementController;
use App\Http\Controllers\SaleController;
use App\Http\Controllers\SaleReturnController;
use App\Http\Controllers\StockController;
use App\Http\Controllers\SupplierPaymentController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\PurchaseReturnController;
use App\Http\Controllers\UserManagementController;
use Illuminate\Support\Facades\Route;

Route::middleware('guest')->group(function (): void {
    Route::get('/login', [AuthController::class, 'showLogin'])->name('login');
    Route::post('/login', [AuthController::class, 'login'])->name('login.attempt');
    Route::get('/forgot-password', [PasswordManagementController::class, 'forgotForm'])->name('password.request');
    Route::post('/forgot-password', [PasswordManagementController::class, 'sendResetLink'])->name('password.email');
    Route::get('/reset-password/{token}', [PasswordManagementController::class, 'resetForm'])->name('password.reset');
    Route::post('/reset-password', [PasswordManagementController::class, 'reset'])->name('password.update');
});

Route::middleware('auth')->group(function (): void {
    Route::post('/logout', [AuthController::class, 'logout'])->name('logout');
    Route::post('/access/preview-role', [AccessPreviewController::class, 'update'])->middleware('ability:users.manage')->name('access.preview-role');
    Route::get('/change-password', [PasswordManagementController::class, 'changeForm'])->name('password.change');
    Route::post('/change-password', [PasswordManagementController::class, 'change'])->name('password.change.update');

    Route::get('/', DashboardController::class)->middleware('ability:dashboard.view')->name('dashboard');
    Route::get('/management-centre', ManagementCentreController::class)->middleware('ability:dashboard.view')->name('management-centre');
    Route::get('/customers', [CustomerController::class, 'index'])->middleware('ability:customers.view')->name('customers.index');
    Route::get('/customers/create', [CustomerController::class, 'create'])->middleware('ability:sales.manage')->name('customers.create');
    Route::post('/customers', [CustomerController::class, 'store'])->middleware('ability:sales.manage')->name('customers.store');
    Route::post('/customers/quick-store', [CustomerController::class, 'quickStore'])->middleware('ability:sales.manage')->name('customers.quick-store');
    Route::get('/customers/{customer}', [CustomerController::class, 'show'])->middleware('ability:customers.view')->name('customers.show');
    Route::get('/customers/{customer}/edit', [CustomerController::class, 'edit'])->middleware('ability:sales.manage')->name('customers.edit');
    Route::put('/customers/{customer}', [CustomerController::class, 'update'])->middleware('ability:sales.manage')->name('customers.update');
    Route::post('/customers/{customer}/status', [CustomerController::class, 'updateStatus'])->middleware('ability:sales.manage')->name('customers.status');
    Route::get('/customers/{customer}/statement', [CustomerController::class, 'statement'])->middleware('ability:customers.statement')->name('customers.statement');
    Route::get('/customers/{customer}/statement/print', [CustomerController::class, 'printStatement'])->middleware('ability:customers.statement')->name('customers.statement.print');
    Route::get('/customers/{customer}/statement/pdf', [CustomerController::class, 'pdfStatement'])->middleware('ability:customers.statement')->name('customers.statement.pdf');
    Route::get('/customers/{customer}/statement/export', [CustomerController::class, 'exportStatement'])->middleware('ability:customers.statement')->name('customers.statement.export');
    Route::get('/suppliers', [SupplierController::class, 'index'])->middleware('ability:suppliers.view')->name('suppliers.index');
    Route::get('/suppliers/create', [SupplierController::class, 'create'])->middleware('ability:purchases.manage')->name('suppliers.create');
    Route::post('/suppliers', [SupplierController::class, 'store'])->middleware('ability:purchases.manage')->name('suppliers.store');
    Route::post('/suppliers/quick-store', [PurchaseController::class, 'quickSupplierStore'])->middleware('ability:purchases.manage')->name('suppliers.quick-store');
    Route::get('/suppliers/{supplier}', [SupplierController::class, 'show'])->middleware('ability:suppliers.view')->name('suppliers.show');
    Route::get('/suppliers/{supplier}/edit', [SupplierController::class, 'edit'])->middleware('ability:purchases.manage')->name('suppliers.edit');
    Route::put('/suppliers/{supplier}', [SupplierController::class, 'update'])->middleware('ability:purchases.manage')->name('suppliers.update');
    Route::post('/suppliers/{supplier}/status', [SupplierController::class, 'updateStatus'])->middleware('ability:purchases.manage')->name('suppliers.status');
    Route::get('/suppliers/{supplier}/statement', [SupplierController::class, 'statement'])->middleware('ability:suppliers.statement')->name('suppliers.statement');
    Route::get('/suppliers/{supplier}/statement/print', [SupplierController::class, 'printStatement'])->middleware('ability:suppliers.statement')->name('suppliers.statement.print');
    Route::get('/suppliers/{supplier}/statement/pdf', [SupplierController::class, 'pdfStatement'])->middleware('ability:suppliers.statement')->name('suppliers.statement.pdf');
    Route::get('/suppliers/{supplier}/statement/export', [SupplierController::class, 'exportStatement'])->middleware('ability:suppliers.statement')->name('suppliers.statement.export');
    Route::get('/products', [ProductController::class, 'index'])->middleware('ability:products.view')->name('products.index');
    Route::get('/products/create', [ProductController::class, 'create'])->middleware('ability:purchases.manage')->name('products.create');
    Route::post('/products', [ProductController::class, 'store'])->middleware('ability:purchases.manage')->name('products.store');
    Route::get('/products/{product}', [ProductController::class, 'show'])->middleware('ability:products.view')->name('products.show');
    Route::get('/products/{product}/edit', [ProductController::class, 'edit'])->middleware('ability:purchases.manage')->name('products.edit');
    Route::put('/products/{product}', [ProductController::class, 'update'])->middleware('ability:purchases.manage')->name('products.update');
    Route::post('/products/{product}/status', [ProductController::class, 'updateStatus'])->middleware('ability:purchases.manage')->name('products.status');
    Route::get('/users', [UserManagementController::class, 'index'])->middleware('ability:users.manage')->name('users.index');
    Route::get('/users/create', [UserManagementController::class, 'create'])->middleware('ability:users.manage')->name('users.create');
    Route::post('/users', [UserManagementController::class, 'store'])->middleware('ability:users.manage')->name('users.store');
    Route::get('/users/{user}/role', [UserManagementController::class, 'editRole'])->middleware('ability:users.manage')->name('users.role.edit');
    Route::put('/users/{user}/role', [UserManagementController::class, 'updateRole'])->middleware('ability:users.manage')->name('users.role.update');
    Route::get('/users/{user}/edit', [UserManagementController::class, 'edit'])->middleware('ability:users.manage')->name('users.edit');
    Route::put('/users/{user}', [UserManagementController::class, 'update'])->middleware('ability:users.manage')->name('users.update');
    Route::get('/roles', [RoleManagementController::class, 'index'])->middleware('ability:users.manage')->name('roles.index');
    Route::get('/permissions', [RoleManagementController::class, 'matrix'])->middleware('ability:users.manage')->name('roles.matrix');
    Route::post('/permissions', [RoleManagementController::class, 'updateMatrix'])->middleware('ability:users.manage')->name('roles.matrix.update');
    Route::get('/roles/{role}/edit', [RoleManagementController::class, 'edit'])->middleware('ability:users.manage')->name('roles.edit');
    Route::put('/roles/{role}', [RoleManagementController::class, 'update'])->middleware('ability:users.manage')->name('roles.update');
    Route::get('/admin/uat-center', [AdminToolkitController::class, 'uatCenter'])->middleware('ability:users.manage')->name('admin.uat-center');
    Route::get('/admin/demo-center', [AdminToolkitController::class, 'demoCenter'])->middleware('ability:users.manage')->name('admin.demo-center');
    Route::get('/admin/readiness', [AdminToolkitController::class, 'readiness'])->middleware('ability:users.manage')->name('admin.readiness');
    Route::get('/follow-ups', [FollowUpController::class, 'index'])->middleware('ability:follow_ups.manage')->name('follow-ups.index');
    Route::get('/follow-ups/create', [FollowUpController::class, 'create'])->middleware('ability:follow_ups.manage')->name('follow-ups.create');
    Route::post('/follow-ups', [FollowUpController::class, 'store'])->middleware('ability:follow_ups.manage')->name('follow-ups.store');
    Route::post('/follow-ups/{followUp}/complete', [FollowUpController::class, 'complete'])->middleware('ability:follow_ups.manage')->name('follow-ups.complete');
    Route::post('/follow-ups/{followUp}/send', [FollowUpController::class, 'send'])->middleware('ability:follow_ups.manage')->name('follow-ups.send');
    Route::get('/activity-logs', [ActivityLogController::class, 'index'])->middleware('ability:activity_logs.view')->name('activity-logs.index');
    Route::get('/settings/business', [BusinessSettingsController::class, 'edit'])->middleware('ability:business.manage')->name('settings.business.edit');
    Route::post('/settings/business', [BusinessSettingsController::class, 'update'])->middleware('ability:business.manage')->name('settings.business.update');
    Route::get('/setup/{resource}', [MasterDataController::class, 'index'])->whereIn('resource', MasterDataController::SUPPORTED_RESOURCES)->middleware('ability:business.manage,master_data.manage')->name('master-data.index');
    Route::post('/setup/{resource}', [MasterDataController::class, 'store'])->whereIn('resource', MasterDataController::SUPPORTED_RESOURCES)->middleware('ability:business.manage,master_data.manage')->name('master-data.store');
    Route::put('/setup/{resource}/{record}', [MasterDataController::class, 'update'])->whereIn('resource', MasterDataController::SUPPORTED_RESOURCES)->middleware('ability:business.manage,master_data.manage')->name('master-data.update');
    Route::post('/setup/{resource}/{record}/status', [MasterDataController::class, 'updateStatus'])->whereIn('resource', MasterDataController::SUPPORTED_RESOURCES)->middleware('ability:business.manage,master_data.manage')->name('master-data.status');
    Route::post('/products/categories/quick-store', [QuickCategoryController::class, 'productCategory'])->middleware('ability:business.manage,master_data.manage')->name('products.categories.quick-store');
    Route::post('/expenses/categories/quick-store', [QuickCategoryController::class, 'expenseCategory'])->middleware('ability:business.manage,master_data.manage')->name('expenses.categories.quick-store');
    Route::get('/reports/customer-aging', [ReportController::class, 'customerAging'])->middleware('ability:reports.view')->name('reports.customer-aging');
    Route::get('/reports/customer-aging/export', [ReportController::class, 'customerAgingExport'])->middleware('ability:reports.view')->name('reports.customer-aging.export');
    Route::get('/reports/supplier-aging', [ReportController::class, 'supplierAging'])->middleware('ability:reports.view')->name('reports.supplier-aging');
    Route::get('/reports/supplier-aging/export', [ReportController::class, 'supplierAgingExport'])->middleware('ability:reports.view')->name('reports.supplier-aging.export');
    Route::get('/reports/financial-summary', [ReportController::class, 'financialSummary'])->middleware('ability:reports.view')->name('reports.financial-summary');
    Route::get('/reports/payment-methods', [ReportController::class, 'paymentMethods'])->middleware('ability:reports.view')->name('reports.payment-methods');
    Route::get('/reports/cashier-performance', [ReportController::class, 'cashierPerformance'])->middleware('ability:reports.view')->name('reports.cashier-performance');
    Route::get('/reports/daily-closing', [ReportController::class, 'dailyClosing'])->middleware('ability:reports.view')->name('reports.daily-closing');
    Route::get('/reports/daily-sales-summary', [ReportController::class, 'dailySalesSummary'])->middleware('ability:reports.view')->name('reports.daily-sales-summary');
    Route::get('/reports/daily-sales-summary/export', [ReportController::class, 'dailySalesSummaryExport'])->middleware('ability:reports.view')->name('reports.daily-sales-summary.export');
    Route::get('/expenses', [ExpenseController::class, 'index'])->middleware('ability:expenses.view')->name('expenses.index');
    Route::get('/expenses/create', [ExpenseController::class, 'create'])->middleware('ability:expenses.manage')->name('expenses.create');
    Route::post('/expenses', [ExpenseController::class, 'store'])->middleware('ability:expenses.manage')->name('expenses.store');
    Route::get('/expenses/{expense}', [ExpenseController::class, 'show'])->middleware('ability:expenses.view')->name('expenses.show');
    Route::get('/expenses/{expense}/print', [ExpenseController::class, 'print'])->middleware('ability:expenses.view')->name('expenses.print');
    Route::get('/cash-shifts', [CashShiftController::class, 'index'])->middleware('ability:cash_shifts.manage')->name('cash-shifts.index');
    Route::get('/cash-shifts/open', [CashShiftController::class, 'create'])->middleware('ability:cash_shifts.manage')->name('cash-shifts.create');
    Route::post('/cash-shifts', [CashShiftController::class, 'store'])->middleware('ability:cash_shifts.manage')->name('cash-shifts.store');
    Route::get('/cash-shifts/{cashShift}', [CashShiftController::class, 'show'])->middleware('ability:cash_shifts.manage')->name('cash-shifts.show');
    Route::get('/cash-shifts/{cashShift}/close', [CashShiftController::class, 'closeForm'])->middleware('ability:cash_shifts.manage')->name('cash-shifts.close-form');
    Route::post('/cash-shifts/{cashShift}/close', [CashShiftController::class, 'close'])->middleware('ability:cash_shifts.manage')->name('cash-shifts.close');
    Route::get('/sales', [SaleController::class, 'index'])->middleware('ability:sales.view')->name('sales.index');
    Route::get('/sales/create', [SaleController::class, 'create'])->middleware('ability:sales.manage')->name('sales.create');
    Route::post('/sales', [SaleController::class, 'store'])->middleware('ability:sales.manage')->name('sales.store');
    Route::get('/sales/{sale}', [SaleController::class, 'show'])->middleware('ability:sales.view')->name('sales.show');
    Route::get('/sales/{sale}/print', [SaleController::class, 'print'])->middleware('ability:sales.view')->name('sales.print');
    Route::get('/sales/{sale}/correct', [SaleController::class, 'correct'])->middleware('ability:sales.manage')->name('sales.correct');
    Route::post('/sales/{sale}/void', [SaleController::class, 'void'])->middleware('ability:sales.manage')->name('sales.void');
    Route::get('/sales/{sale}/returns/create', [SaleReturnController::class, 'create'])->middleware('ability:sales.manage')->name('sales.returns.create');
    Route::post('/sales/{sale}/returns', [SaleReturnController::class, 'store'])->middleware('ability:sales.manage')->name('sales.returns.store');
    Route::get('/sale-returns/{saleReturn}', [SaleReturnController::class, 'show'])->middleware('ability:sales.view')->name('sale-returns.show');
    Route::get('/sale-returns/{saleReturn}/print', [SaleReturnController::class, 'print'])->middleware('ability:sales.view')->name('sale-returns.print');
    Route::get('/purchases', [PurchaseController::class, 'index'])->middleware('ability:purchases.view')->name('purchases.index');
    Route::get('/purchases/create', [PurchaseController::class, 'create'])->middleware('ability:purchases.manage')->name('purchases.create');
    Route::post('/purchases', [PurchaseController::class, 'store'])->middleware('ability:purchases.manage')->name('purchases.store');
    Route::get('/purchases/{purchase}', [PurchaseController::class, 'show'])->middleware('ability:purchases.view')->name('purchases.show');
    Route::get('/purchases/{purchase}/print', [PurchaseController::class, 'print'])->middleware('ability:purchases.view')->name('purchases.print');
    Route::get('/purchases/{purchase}/correct', [PurchaseController::class, 'correct'])->middleware('ability:purchases.manage')->name('purchases.correct');
    Route::post('/purchases/{purchase}/void', [PurchaseController::class, 'void'])->middleware('ability:purchases.manage')->name('purchases.void');
    Route::get('/purchases/{purchase}/returns/create', [PurchaseReturnController::class, 'create'])->middleware('ability:purchases.manage')->name('purchases.returns.create');
    Route::post('/purchases/{purchase}/returns', [PurchaseReturnController::class, 'store'])->middleware('ability:purchases.manage')->name('purchases.returns.store');
    Route::get('/purchase-returns/{purchaseReturn}', [PurchaseReturnController::class, 'show'])->middleware('ability:purchases.view')->name('purchase-returns.show');
    Route::get('/purchase-returns/{purchaseReturn}/print', [PurchaseReturnController::class, 'print'])->middleware('ability:purchases.view')->name('purchase-returns.print');
    Route::get('/capital-inputs', [CapitalEntryController::class, 'index'])->middleware('ability:capital.view')->name('capital.index');
    Route::get('/capital-inputs/create', [CapitalEntryController::class, 'create'])->middleware('ability:capital.manage')->name('capital.create');
    Route::post('/capital-inputs', [CapitalEntryController::class, 'store'])->middleware('ability:capital.manage')->name('capital.store');
    Route::get('/stock/balances', [StockController::class, 'balances'])->middleware('ability:stock.view')->name('stock.balances');
    Route::get('/stock/balances/export', [StockController::class, 'balancesExport'])->middleware('ability:stock.view')->name('stock.balances.export');
    Route::get('/stock/reorder', [StockController::class, 'reorder'])->middleware('ability:stock.view')->name('stock.reorder');
    Route::get('/stock/reorder/export', [StockController::class, 'reorderExport'])->middleware('ability:stock.view')->name('stock.reorder.export');
    Route::get('/stock/transfers', [StockController::class, 'transfersIndex'])->middleware('ability:stock.view')->name('stock.transfers.index');
    Route::get('/stock/adjustments', [StockController::class, 'adjustmentsIndex'])->middleware('ability:stock.view')->name('stock.adjustments.index');
    Route::get('/stock/counts', [StockController::class, 'countsIndex'])->middleware('ability:stock.view')->name('stock.counts.index');
    Route::get('/stock/products/{product}/history', [StockController::class, 'productHistory'])->middleware('ability:stock.view')->name('stock.product-history');
    Route::get('/stock/items/{productUnit}/history', [StockController::class, 'history'])->middleware('ability:stock.view')->name('stock.history');
    Route::get('/stock/items/{productUnit}/history/export', [StockController::class, 'historyExport'])->middleware('ability:stock.view')->name('stock.history.export');
    Route::get('/stock/transfers/create', [StockController::class, 'transferCreate'])->middleware('ability:stock.manage')->name('stock.transfers.create');
    Route::post('/stock/transfers', [StockController::class, 'transferStore'])->middleware('ability:stock.manage')->name('stock.transfers.store');
    Route::get('/stock/transfers/{referenceNo}', [StockController::class, 'transferShow'])->middleware('ability:stock.view')->name('stock.transfers.show');
    Route::get('/stock/transfers/{referenceNo}/print', [StockController::class, 'transferPrint'])->middleware('ability:stock.view')->name('stock.transfers.print');
    Route::get('/stock/adjustments/create', [StockController::class, 'adjustmentCreate'])->middleware('ability:stock.manage')->name('stock.adjustments.create');
    Route::post('/stock/adjustments', [StockController::class, 'adjustmentStore'])->middleware('ability:stock.manage')->name('stock.adjustments.store');
    Route::get('/stock/adjustments/{referenceNo}', [StockController::class, 'adjustmentShow'])->middleware('ability:stock.view')->name('stock.adjustments.show');
    Route::get('/stock/adjustments/{referenceNo}/print', [StockController::class, 'adjustmentPrint'])->middleware('ability:stock.view')->name('stock.adjustments.print');
    Route::get('/stock/counts/create', [StockController::class, 'countCreate'])->middleware('ability:stock.manage')->name('stock.counts.create');
    Route::post('/stock/counts', [StockController::class, 'countStore'])->middleware('ability:stock.manage')->name('stock.counts.store');
    Route::get('/stock/counts/{referenceNo}', [StockController::class, 'countShow'])->middleware('ability:stock.view')->name('stock.counts.show');
    Route::get('/stock/counts/{referenceNo}/print', [StockController::class, 'countPrint'])->middleware('ability:stock.view')->name('stock.counts.print');
    Route::get('/customer-payments', [CustomerPaymentController::class, 'index'])->middleware('ability:customer_payments.manage')->name('customer-payments.index');
    Route::get('/customer-payments/create', [CustomerPaymentController::class, 'create'])->middleware('ability:customer_payments.manage')->name('customer-payments.create');
    Route::get('/customer-payments/{customerPayment}', [CustomerPaymentController::class, 'show'])->middleware('ability:customer_payments.manage')->name('customer-payments.show');
    Route::get('/customer-payments/{customerPayment}/print', [CustomerPaymentController::class, 'print'])->middleware('ability:customer_payments.manage')->name('customer-payments.print');
    Route::post('/customer-payments', [CustomerPaymentController::class, 'store'])->middleware('ability:customer_payments.manage')->name('customer-payments.store');
    Route::get('/supplier-payments', [SupplierPaymentController::class, 'index'])->middleware('ability:supplier_payments.manage')->name('supplier-payments.index');
    Route::get('/supplier-payments/create', [SupplierPaymentController::class, 'create'])->middleware('ability:supplier_payments.manage')->name('supplier-payments.create');
    Route::get('/supplier-payments/{supplierPayment}', [SupplierPaymentController::class, 'show'])->middleware('ability:supplier_payments.manage')->name('supplier-payments.show');
    Route::get('/supplier-payments/{supplierPayment}/print', [SupplierPaymentController::class, 'print'])->middleware('ability:supplier_payments.manage')->name('supplier-payments.print');
    Route::post('/supplier-payments', [SupplierPaymentController::class, 'store'])->middleware('ability:supplier_payments.manage')->name('supplier-payments.store');
});
